site_name: Tối ưu server Minecraft
site_author: minhh2792
site_description: Một chiếc guide nhỏ xinh giúp bạn dễ dàng hơn trong việc tối ưu server
site_url: https://minhh2792.is-a.dev/mcvn-optimization-guide/
nav:
  - Trang chủ: index.md
  - Giải thích thuật ngữ: term-explanation.md
  - Ảnh hưởng của TPS: tps-lag.md
  - Lựa chọn phần cứng: choosing-hardware.md
  - Lựa chọn hệ điều hành: choosing-os.md
  - Lựa chọn Server Software: choosing-server-software.md
  - Lựa chọn host cho server: choosing-a-host.md
  - Startup Flags: startup-flags.md
  - Mob Stacker: mob-stacker.md
  - Sử dụng Profiler: profiler-tools.md
  - "Configuration":
      - "Bukkit": "configuration/bukkit.md"
      - "Spigot": "configuration/spigot.md"
      - "Paper": "configuration/paper.md"
      - "Purpur": "configuration/purpur.md"
      - "Pearl": "configuration/pearl.md"

theme:
  name: material
  language: vi
  favicon: assets/images/favicon.ico
  custom_dir: overrides
  palette:
    scheme: slate
  font:
    text: Jetbrains Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/minhh2792
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/541245686478536726
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/minhh2792

repo_url: https://github.com/minhh2792/mcvn-optimization-guide
repo_name: mcvn-optimization-guide
edit_uri: edit/main/docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: Made with ♥️ by minhh2792 for my belove community
