name: Build and deploy
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      
      - name: Build and deploy
        run: |
          pip install -r requirements.txt
          mkdocs gh-deploy --force